// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmBdi6liOfUFOO5QqOA_0N5TgIMf_NBik',
    appId: '1:10162701933:web:93a35b4685d8e82618a164',
    messagingSenderId: '10162701933',
    projectId: 'sst-logistics-app',
    authDomain: 'sst-logistics-app.firebaseapp.com',
    storageBucket: 'sst-logistics-app.firebasestorage.app',
    measurementId: 'G-WRLXKMHB5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhbqEzKm7hGsiMzKwASe83F_fVxRqaGqo',
    appId: '1:10162701933:android:2aaff051401f560018a164',
    messagingSenderId: '10162701933',
    projectId: 'sst-logistics-app',
    storageBucket: 'sst-logistics-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM6_dxnhKOLh9MWJy7NlWTY9J6iG9-ivU',
    appId: '1:10162701933:ios:7ab2925fc567dbb218a164',
    messagingSenderId: '10162701933',
    projectId: 'sst-logistics-app',
    storageBucket: 'sst-logistics-app.firebasestorage.app',
    iosBundleId: 'com.sttlogistics.group',
  );
}
